### ISSUE TITLE
Jest moduleNameMapper does not apply unless config is placed in package.json file

### ISSUE THREAD

**Issue by Peter-holyoke** [ProvidenceGeeks/website-frontend#12]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

An issue was observed during the development of #10 that prevented the configuration of CSS module mapping being placed in _jest.config.json_.  When this was added to that file
```javascript
  "jest": {
    "moduleNameMapper": {
      "\\.(css|scss)$": "<rootDir>/test/__mocks__/style-mock.js"
    }
  }
``` 

the following error was observed
```bash
@font-face {
    ^
    
    SyntaxError: Invalid or unexpected token
```

The following code must be placed into _package.json_ for now.

**Comment by thescientist13** [comment]
Couple other things I noticed, when running with `--coverage` flag
```
$ yarn run test -- --coverage
yarn run v0.21.3
$ jest --coverage
 PASS  src/components/bootstrap/bootstrap.spec.js
 PASS  src/components/hello-world/hello.spec.js
 PASS  src/views/home/home.spec.js

Test Suites: 3 passed, 3 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.351s
Ran all test suites.
----------------------------|----------|----------|----------|----------|----------------|
File                        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------------|----------|----------|----------|----------|----------------|
All files                   |       90 |      100 |    85.71 |       90 |                |
 src/components/bootstrap   |      100 |      100 |      100 |      100 |                |
  bootstrap.js              |      100 |      100 |      100 |      100 |                |
 src/components/hello-world |      100 |      100 |      100 |      100 |                |
  hello.js                  |      100 |      100 |      100 |      100 |                |
 src/views/home             |      100 |      100 |      100 |      100 |                |
  home.js                   |      100 |      100 |      100 |      100 |                |
 test/shims                 |       50 |      100 |        0 |       50 |                |
  react-raf-shim.js         |       50 |      100 |        0 |       50 |              4 |
----------------------------|----------|----------|----------|----------|----------------|
```

1.  coverage output directory is not being respected.  Instead coverage is output to _coverage/_
1.  the shim in _test/_ is being covered

Both these contradict our configuration file

**Comment by thescientist13** [comment]
@Peter-holyoke 
Looking at the jest docs, I wonder if the issue is that the default file need to be _.js_, NOT _.json_
https://facebook.github.io/jest/docs/en/configuration.html
> Jest's configuration can be defined in the package.json file of your project, **_or through a jest.config.js file_** or through the --config <path/to/js|json> option. If you'd like to use your package.json to store Jest's config, the "jest" key should be used on the top level so Jest will know how to find your settings:

I think we might just need to to try renaming the file?

**Comment by Peter-holyoke** [comment]
I gave that a try, and got the same results. With or without the --config flag.

**Comment by thescientist13** [comment]
@Peter-holyoke 
So just to confirm, did you trying using `--config` like this?
```
"test": "jest --config ./jest.config.json"
```

I ran that and got these errors
```
$ yarn run test
yarn run v1.2.1
$ jest --config ./jest.config.json
 FAIL  src/views/home/home.spec.js
  ● Test suite failed to run

    /Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/src/views/home/home.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as React from 'react';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at next (native)

 FAIL  src/components/hello-world/hello.spec.js
  ● Test suite failed to run

    /Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/src/components/hello-world/hello.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as React from 'react';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at next (native)

 FAIL  src/components/bootstrap/bootstrap.spec.js
  ● Test suite failed to run

    /Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/src/components/bootstrap/bootstrap.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as React from 'react';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:305:17)
      at next (native)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        1.056s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So I think we need to work on this, since I think we've just been lucky getting by on Jest defaults
