### ISSUE TITLE
resolve jest SyntaxError console message

### ISSUE THREAD

**Issue by thescientist13** [ProvidenceGeeks/website-frontend#49]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary

As seen in #47 , when running `yarn run test`, this is observed, though there nothing breaks
```
src/components/bootstrap/bootstrap.spec.jsx
  Bootstrap Component
    ✓ should not be null (2ms)
    ✓ should have a Header Component (2ms)
    ✓ should have a Home Component (2ms)
    ✓ should have a Footer Component (1ms)

  console.log src/views/home/home.jsx:15
    SyntaxError
        at XMLHttpRequest.open (/Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:486:15)
        at dispatchXhrRequest (/Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/node_modules/axios/lib/adapters/xhr.js:46:13)
        at xhrAdapter (/Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/node_modules/axios/lib/adapters/xhr.js:12:10)
        at dispatchRequest (/Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/node_modules/axios/lib/core/dispatchRequest.js:59:10)
        at process._tickCallback (internal/process/next_tick.js:103:7)

  console.log src/views/home/home.jsx:15
    SyntaxError
        at XMLHttpRequest.open (/Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:486:15)
        at dispatchXhrRequest (/Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/node_modules/axios/lib/adapters/xhr.js:46:13)
        at xhrAdapter (/Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/node_modules/axios/lib/adapters/xhr.js:12:10)
        at dispatchRequest (/Users/obuckley/Workspace/providencegeeks.com/repo/website-frontend/node_modules/axios/lib/core/dispatchRequest.js:59:10)
```

**Comment by thescientist13** [comment]
only an update to `.spec` files.
